# Tokens
bearer_token = "AAAAAAAAAAAAAAAAAAAAACPOXAEAAAAAkz879L%2FFC%2B7e1hPmAFeSFor1AT0%3DA3zJhVqvMCBelUzLOyQ6K086HQqo5hsRWYtHJJC2DbOlkiElxx"
consumer_key = "ua4jrmNNStVQdMXAFYUgeoiiP"
consumer_secret = "s5zUdmxlV9mDbXJyt0RwaXIrrPMuZAEMz2csc6dOLDpCxRSzh4"
